name: "Build & Rubocop"
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password

    container:
      image: ruby:3.0.4
      env:
        RAILS_ENV: test
        POSTGRES_HOST: postgres

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Bundler set up
        run: |
          gem install bundler
          bundle config set path 'vendor/bundle'
          bundle check || bundle install -j4
      - name: Run rubocop
        run: bundle exec rubocop
